### ISSUE TITLE
no module Airtable

### ISSUE THREAD

**Issue by gnoe8307** [josephbestjames/airtable.py#10]
hi,

I have installed your module by doing 
"pip install airtable"

that worked fine.

however no module call Airtable is to be found:

> from airtable import Airtable
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: cannot import name 'Airtable'

what's the issue?

thx

**Comment by 21stio** [comment]
Just had a look in the tests. It works if you import it via `from airtable import airtable`

**Comment by gnoe8307** [comment]
ok, thanks, I got confused.

I made it work with 

> from airtable.airtable import Airtable

**Comment by daveaseeman** [comment]
@21stio still not working for me - I have `from airtable import airtable' but get the message:
```
ImportError: cannot import name airtable
```

**Comment by ezcitron** [comment]
@daveaseeman I am getting the same error message that you got:

`from airtable import Airtable`

`ImportError: cannot import name 'Airtable'`

I have also tried:

`from airtable import airtable` and I get an analogous error message.

This also doesn't work:

`from airtable.airtable import Airtable`

because:

`ModuleNotFoundError: No module named 'airtable.airtable'; 'airtable' is not a package`

What did you change to make it work? Or is it possible that the module has been changed substantially over the past year?
Thanks.

**Comment by daveaseeman** [comment]
Unfortunately, I honestly don’t remember and I don’t have time to look back now. However, I just made my repository public so you can check it out and see what I did. Whatever it was, I remember I got it working.

https://github.com/daveaseeman/airgantt

**Comment by ezcitron** [comment]
@daveseeman, thanks so much for the response. no worries, I just got it to work...noob mistake, i had named one of my scripts airtable.py so when I imported the module it was trying to import my script. it's working great now :)

**Comment by daveaseeman** [comment]
Haha glad you solved it!

**Comment by h** [comment]
It's a bit surprising that the import is "from airtable.airtable import Airtable" instead of "from airtable import Airtable".

I'd suggest fixing that with this pull request: #24
